server:
  port: 8082
spring:
  application:
    name: CLAZZ
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  #配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/class-web
    username: root
    password: root
mybatis:
  mapper-locations: classpath:/com/zb/dao/*Dao.xml
  type-aliases-package: com.zb.entity

#配置日志信息
logging:
  level:
    com.zb: debug

upload.dir: D:\\桌面\\codes\\class-web-parent\\class-clazz\\files